In [17]:
# Import necessary libraries
# import PyPDF2
# import re
# import nltk
# from nltk.tokenize import word_tokenize
# from nltk.tag import pos_tag
# from nltk.chunk import ne_chunk
# import fitz  # PyMuPDF
# Dashboarding
# import dash
# from dash import dcc
# from dash import html
# from dash.dependencies import Input, Output

# PDF Extractor
import tabula
# Data Manipulation
import pandas as pd
import numpy as np

In [18]:
# Ensure necessary NLTK models are downloaded
#nltk.download('punkt')
#nltk.download('maxent_ne_chunker')
#nltk.download('words')

In [21]:
def extract_and_combine_tables(pdf_path, page_numbers, new_header):
    combined_table = pd.DataFrame()
    
    for page in page_numbers:
        # Extract table from each page
        tables = tabula.read_pdf(pdf_path, pages=page, multiple_tables=True, lattice=True)
        
        if tables:
            df = tables[0]
            # Delete the first three rows from each page
            df = df.iloc[3:]
            combined_table = pd.concat([combined_table, df], ignore_index=True)
    # Keep only the first 5 columns
    combined_table = combined_table.iloc[:, :5]  

    # Set the new header for the combined table
    combined_table.columns = new_header
    
    return combined_table

# Specify your PDF path
pdf_path = '/Users/mohjaiswal/Desktop/ArthyaInvest/dvdfdf.pdf'
pages = [18, 19]  # Pages to extract
new_header = [
    "Profit and Loss", 
    "As at September 30, 2020", 
    "As at March 31, 2020", 
    "As at March 31, 2019", 
    "As at March 31, 2018"
]

# Call the function and assign the result to a variable
df = extract_and_combine_tables(pdf_path, pages, new_header)

# Display the DataFrame
df

,Profit and Loss,"As at September 30, 2020","As at March 31, 2020","As at March 31, 2019","As at March 31, 2018"
0,Income,NaN,NaN,NaN,NaN
1,Revenue from operations,"2,004.57","2,475.09","1,696.98","1,720.40"
2,Other income,65.49,146.37,164.00,99.00
3,Total income,"2,070.06","2,621.46","1,860.98","1,819.40"
4,NaN,NaN,NaN,NaN,NaN
5,Expenses,NaN,NaN,NaN,NaN
6,"Content, event and web server",151.97,506.92,442.95,121.35
7,Advertising and promotion,"1,196.24","1,329.26",272.48,427.80
8,Commission,222.66,70.72,31.31,32.26
9,Employee benefits,218.54,318.67,413.84,371.97
10,Finance costs,5.11,12.37,13.84,18.34
11,Depreciation and amortization,187.23,268.81,195.44,82.16
12,Others,154.10,304.75,372.94,279.84
13,Total expenses,"2,135.85","2,811.50","1,742.80","1,333.72"
14,NaN,NaN,NaN,NaN,NaN
15,"Profit/(Loss) before exceptional items, share ...",(65.79),(190.04),118.18,485.68
16,Share of loss of Investments accounted using e...,(15.92),(18.12),(9.47),(0.63)
17,(Loss)/profit before exceptional items and tax,(81.71),(208.16),108.71,485.05
18,Exceptional items,-,-,-,(357.18)
19,(Loss)/profit before tax,(81.71),(208.16),108.71,127.87
20,Tax expense:,NaN,NaN,NaN,NaN
21,Current tax,45.81,55.57,69.65,143.65
22,Deferred tax,(26.45),2.42,(28.07),(26.01)
23,Total tax expense,19.36,57.99,41.58,117.64
24,NaN,NaN,NaN,NaN,NaN
25,Net (loss)/profit,(101.07),(266.15),67.13,10.23
26,NaN,NaN,NaN,NaN,NaN
27,Other comprehensive income,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN
29,Items that will not be reclassified to profit ...,NaN,NaN,NaN,NaN
30,Re-measurements of defined employee benefit plans,0.34,1.00,(1.69),0.21
31,Income tax relating to items that will not be ...,(0.38),(0.27),(0.45),(0.07)
32,Items that may be reclassified to profit or loss:,NaN,NaN,NaN,NaN
33,Net profit/(loss) on FVOCI debt instruments,(1.34),14.38,0.23,(1.31)
34,Exchange differences in translating the financ...,(41.38),146.19,114.81,16.81
35,Income tax relating to items that will be recl...,-,-,-,-
36,Total other comprehensive income/(loss),(42.46),161.30,112.90,15.64
37,NaN,NaN,NaN,NaN,NaN
38,Total comprehensive income/(loss),(143.53),(104.85),180.03,25.87
39,NaN,NaN,NaN,NaN,NaN
40,Profit/(loss) attributable to:,NaN,NaN,NaN,NaN
41,(i) Equity holders of the Company,(50.15),(21.26),175.08,26.70
42,(ii) Non-controlling interest,(50.92),(244.89),(107.95),(16.47)
43,NaN,NaN,NaN,NaN,NaN
44,Other comprehensive income/(loss) attributable...,NaN,NaN,NaN,NaN
45,(i) Equity holders of the Company,(42.46),161.30,112.90,15.64
46,(ii) Non-controlling interest,-,-,-,-
47,NaN,NaN,NaN,NaN,NaN
48,Total comprehensive income/(loss) attributable...,NaN,NaN,NaN,NaN
49,(i) Equity holders of the Company,(92.61),140.04,287.98,42.34
50,(ii) Non-controlling interest,(50.92),(244.89),(107.95),(16.47)
51,NaN,NaN,NaN,NaN,NaN
52,Earnings per equity share (nominal value of `4...,NaN,NaN,NaN,NaN
53,Basic,(1.78),(0.77),6.39,1.05
54,Diluted,(1.78),(0.77),6.27,1.04

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Profit and Loss           45 non-null     object
 1   As at September 30, 2020  35 non-null     object
 2   As at March 31, 2020      35 non-null     object
 3   As at March 31, 2019      35 non-null     object
 4   As at March 31, 2018      35 non-null     object
dtypes: object(5)
memory usage: 2.3+ KB

In [5]:
# Copy the DataFrame
indexed_df = df.copy()

# Set 'Balance Sheet' as the new index for the copied DataFrame
indexed_df.set_index('Profit and Loss', inplace=True)

# Now, indexed_df will have 'Balance Sheet' as its index
# Display the indexed DataFrame to verify the changes
# Set the maximum number of rows to display all the important data points
pd.set_option('display.max_rows', 100)

# Now when you display the DataFrame, all 100 rows will be shown
indexed_df

,"As at September 30, 2020","As at March 31, 2020","As at March 31, 2019","As at March 31, 2018"
Profit and Loss,,,,
Income,NaN,NaN,NaN,NaN
Revenue from operations,"2,004.57","2,475.09","1,696.98","1,720.40"
Other income,65.49,146.37,164.00,99.00
Total income,"2,070.06","2,621.46","1,860.98","1,819.40"
NaN,NaN,NaN,NaN,NaN
Expenses,NaN,NaN,NaN,NaN
"Content, event and web server",151.97,506.92,442.95,121.35
Advertising and promotion,"1,196.24","1,329.26",272.48,427.80
Commission,222.66,70.72,31.31,32.26
Employee benefits,218.54,318.67,413.84,371.97
Finance costs,5.11,12.37,13.84,18.34
Depreciation and amortization,187.23,268.81,195.44,82.16
Others,154.10,304.75,372.94,279.84
Total expenses,"2,135.85","2,811.50","1,742.80","1,333.72"
NaN,NaN,NaN,NaN,NaN
"Profit/(Loss) before exceptional items, share of net\rprofit/(losses) of investments accounted for using the\requity method and tax",(65.79),(190.04),118.18,485.68
Share of loss of Investments accounted using equity\rmethod (net),(15.92),(18.12),(9.47),(0.63)
(Loss)/profit before exceptional items and tax,(81.71),(208.16),108.71,485.05
Exceptional items,-,-,-,(357.18)
(Loss)/profit before tax,(81.71),(208.16),108.71,127.87
Tax expense:,NaN,NaN,NaN,NaN
Current tax,45.81,55.57,69.65,143.65
Deferred tax,(26.45),2.42,(28.07),(26.01)
Total tax expense,19.36,57.99,41.58,117.64
NaN,NaN,NaN,NaN,NaN
Net (loss)/profit,(101.07),(266.15),67.13,10.23
NaN,NaN,NaN,NaN,NaN
Other comprehensive income,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN
Items that will not be reclassified to profit and loss:,NaN,NaN,NaN,NaN
Re-measurements of defined employee benefit plans,0.34,1.00,(1.69),0.21
Income tax relating to items that will not be reclassified to\rprofit or loss,(0.38),(0.27),(0.45),(0.07)
Items that may be reclassified to profit or loss:,NaN,NaN,NaN,NaN
Net profit/(loss) on FVOCI debt instruments,(1.34),14.38,0.23,(1.31)
Exchange differences in translating the financial\rstatements of a foreign operation,(41.38),146.19,114.81,16.81
Income tax relating to items that will be reclassified to\rprofit and loss,-,-,-,-
Total other comprehensive income/(loss),(42.46),161.30,112.90,15.64
NaN,NaN,NaN,NaN,NaN
Total comprehensive income/(loss),(143.53),(104.85),180.03,25.87
NaN,NaN,NaN,NaN,NaN
Profit/(loss) attributable to:,NaN,NaN,NaN,NaN
(i) Equity holders of the Company,(50.15),(21.26),175.08,26.70
(ii) Non-controlling interest,(50.92),(244.89),(107.95),(16.47)
NaN,NaN,NaN,NaN,NaN
Other comprehensive income/(loss) attributable to:,NaN,NaN,NaN,NaN
(i) Equity holders of the Company,(42.46),161.30,112.90,15.64
(ii) Non-controlling interest,-,-,-,-
NaN,NaN,NaN,NaN,NaN
Total comprehensive income/(loss) attributable to:,NaN,NaN,NaN,NaN
(i) Equity holders of the Company,(92.61),140.04,287.98,42.34
(ii) Non-controlling interest,(50.92),(244.89),(107.95),(16.47)
NaN,NaN,NaN,NaN,NaN
Earnings per equity share (nominal value of `4 each):,NaN,NaN,NaN,NaN
Basic,(1.78),(0.77),6.39,1.05
Diluted,(1.78),(0.77),6.27,1.04

In [6]:
# Remove backticks from the index
indexed_df.index = indexed_df.index.astype(str).str.replace('`', '')

# Check the result
print(indexed_df.index)

Index(['Income', 'Revenue from operations', 'Other income', 'Total income',
       'nan', 'Expenses', 'Content, event and web server',
       'Advertising and promotion', 'Commission', 'Employee benefits',
       'Finance costs', 'Depreciation and amortization', 'Others',
       'Total expenses', 'nan',
       'Profit/(Loss) before exceptional items, share of net\rprofit/(losses) of investments accounted for using the\requity method and tax',
       'Share of loss of Investments accounted using equity\rmethod (net)',
       '(Loss)/profit before exceptional items and tax', 'Exceptional items',
       '(Loss)/profit before tax', 'Tax expense:', 'Current tax',
       'Deferred tax', 'Total tax expense', 'nan', 'Net (loss)/profit', 'nan',
       'Other comprehensive income', 'nan',
       'Items that will not be reclassified to profit and loss:',
       'Re-measurements of defined employee benefit plans',
       'Income tax relating to items that will not be reclassified to\rprofit or loss',
       'Items that may be reclassified to profit or loss:',
       'Net profit/(loss) on FVOCI debt instruments',
       'Exchange differences in translating the financial\rstatements of a foreign operation',
       'Income tax relating to items that will be reclassified to\rprofit and loss',
       'Total other comprehensive income/(loss)', 'nan',
       'Total comprehensive income/(loss)', 'nan',
       'Profit/(loss) attributable to:', '(i) Equity holders of the Company',
       '(ii) Non-controlling interest', 'nan',
       'Other comprehensive income/(loss) attributable to:',
       '(i) Equity holders of the Company', '(ii) Non-controlling interest',
       'nan', 'Total comprehensive income/(loss) attributable to:',
       '(i) Equity holders of the Company', '(ii) Non-controlling interest',
       'nan', 'Earnings per equity share (nominal value of 4 each):', 'Basic',
       'Diluted'],
      dtype='object', name='Profit and Loss')

In [7]:
indexed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, Income to Diluted
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   As at September 30, 2020  35 non-null     object
 1   As at March 31, 2020      35 non-null     object
 2   As at March 31, 2019      35 non-null     object
 3   As at March 31, 2018      35 non-null     object
dtypes: object(4)
memory usage: 2.1+ KB

In [8]:
# Define a function to clean and convert the values to float
def clean_convert_value(x):
    if isinstance(x, str):
        if x == '-':
            # Convert '-' to NaN
            return np.nan
        x = x.replace('₹', '').replace(',', '')
        if '(' in x and ')' in x:
            return -float(x.replace('(', '').replace(')', ''))
        else:
            return float(x)
    elif pd.isna(x):
        return x
    else:
        return float(x)

# Convert columns 0 to 3 to float
for column in indexed_df.columns[0:4]:  # Selecting columns 0 to 3
    indexed_df[column] = indexed_df[column].apply(clean_convert_value)

# Check the data types and DataFrame
print(indexed_df.dtypes)
indexed_df

As at September 30, 2020    float64
As at March 31, 2020        float64
As at March 31, 2019        float64
As at March 31, 2018        float64
dtype: object

,"As at September 30, 2020","As at March 31, 2020","As at March 31, 2019","As at March 31, 2018"
Profit and Loss,,,,
Income,NaN,NaN,NaN,NaN
Revenue from operations,2004.57,2475.09,1696.98,1720.40
Other income,65.49,146.37,164.00,99.00
Total income,2070.06,2621.46,1860.98,1819.40
nan,NaN,NaN,NaN,NaN
Expenses,NaN,NaN,NaN,NaN
"Content, event and web server",151.97,506.92,442.95,121.35
Advertising and promotion,1196.24,1329.26,272.48,427.80
Commission,222.66,70.72,31.31,32.26
Employee benefits,218.54,318.67,413.84,371.97
Finance costs,5.11,12.37,13.84,18.34
Depreciation and amortization,187.23,268.81,195.44,82.16
Others,154.10,304.75,372.94,279.84
Total expenses,2135.85,2811.50,1742.80,1333.72
nan,NaN,NaN,NaN,NaN
"Profit/(Loss) before exceptional items, share of net\rprofit/(losses) of investments accounted for using the\requity method and tax",-65.79,-190.04,118.18,485.68
Share of loss of Investments accounted using equity\rmethod (net),-15.92,-18.12,-9.47,-0.63
(Loss)/profit before exceptional items and tax,-81.71,-208.16,108.71,485.05
Exceptional items,NaN,NaN,NaN,-357.18
(Loss)/profit before tax,-81.71,-208.16,108.71,127.87
Tax expense:,NaN,NaN,NaN,NaN
Current tax,45.81,55.57,69.65,143.65
Deferred tax,-26.45,2.42,-28.07,-26.01
Total tax expense,19.36,57.99,41.58,117.64
nan,NaN,NaN,NaN,NaN
Net (loss)/profit,-101.07,-266.15,67.13,10.23
nan,NaN,NaN,NaN,NaN
Other comprehensive income,NaN,NaN,NaN,NaN
nan,NaN,NaN,NaN,NaN
Items that will not be reclassified to profit and loss:,NaN,NaN,NaN,NaN
Re-measurements of defined employee benefit plans,0.34,1.00,-1.69,0.21
Income tax relating to items that will not be reclassified to\rprofit or loss,-0.38,-0.27,-0.45,-0.07
Items that may be reclassified to profit or loss:,NaN,NaN,NaN,NaN
Net profit/(loss) on FVOCI debt instruments,-1.34,14.38,0.23,-1.31
Exchange differences in translating the financial\rstatements of a foreign operation,-41.38,146.19,114.81,16.81
Income tax relating to items that will be reclassified to\rprofit and loss,NaN,NaN,NaN,NaN
Total other comprehensive income/(loss),-42.46,161.30,112.90,15.64
nan,NaN,NaN,NaN,NaN
Total comprehensive income/(loss),-143.53,-104.85,180.03,25.87
nan,NaN,NaN,NaN,NaN
Profit/(loss) attributable to:,NaN,NaN,NaN,NaN
(i) Equity holders of the Company,-50.15,-21.26,175.08,26.70
(ii) Non-controlling interest,-50.92,-244.89,-107.95,-16.47
nan,NaN,NaN,NaN,NaN
Other comprehensive income/(loss) attributable to:,NaN,NaN,NaN,NaN
(i) Equity holders of the Company,-42.46,161.30,112.90,15.64
(ii) Non-controlling interest,NaN,NaN,NaN,NaN
nan,NaN,NaN,NaN,NaN
Total comprehensive income/(loss) attributable to:,NaN,NaN,NaN,NaN
(i) Equity holders of the Company,-92.61,140.04,287.98,42.34
(ii) Non-controlling interest,-50.92,-244.89,-107.95,-16.47
nan,NaN,NaN,NaN,NaN
Earnings per equity share (nominal value of 4 each):,NaN,NaN,NaN,NaN
Basic,-1.78,-0.77,6.39,1.05
Diluted,-1.78,-0.77,6.27,1.04

In [9]:
indexed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, Income to Diluted
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   As at September 30, 2020  32 non-null     float64
 1   As at March 31, 2020      32 non-null     float64
 2   As at March 31, 2019      32 non-null     float64
 3   As at March 31, 2018      33 non-null     float64
dtypes: float64(4)
memory usage: 2.1+ KB

In [10]:
# Define the number of years for CAGR calculation
years = 2  # Adjust this based on your specific data

# Your existing code for calculations
def calculate_change(current, previous):
    if pd.notna(current) and pd.notna(previous) and previous != 0:
        return (current - previous) / previous * 100
    else:
        return 0

indexed_df['YoY 2019-2020'] = indexed_df.apply(lambda row: calculate_change(row[1], row[2]), axis=1)
indexed_df['YoY 2018-2019'] = indexed_df.apply(lambda row: calculate_change(row[2], row[3]), axis=1)
indexed_df['CAGR'] = indexed_df.apply(lambda row: ((row[1] / row[3]) ** (1 / years) - 1) * 100 if pd.notna(row[1]) and pd.notna(row[3]) and row[3] != 0 else 0, axis=1)

# Display the updated DataFrame
indexed_df

/Users/mohjaiswal/opt/anaconda3/envs/dev2/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]

,"As at September 30, 2020","As at March 31, 2020","As at March 31, 2019","As at March 31, 2018",YoY 2019-2020,YoY 2018-2019,CAGR
Profit and Loss,,,,,,,
Income,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Revenue from operations,2004.57,2475.09,1696.98,1720.40,45.852632,-1.361311,19.944622
Other income,65.49,146.37,164.00,99.00,-10.750000,65.656566,21.592962
Total income,2070.06,2621.46,1860.98,1819.40,40.864491,2.285369,20.034897
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Expenses,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
"Content, event and web server",151.97,506.92,442.95,121.35,14.441811,265.018541,104.385378
Advertising and promotion,1196.24,1329.26,272.48,427.80,387.837639,-36.306685,76.272506
Commission,222.66,70.72,31.31,32.26,125.870329,-2.944823,48.060409
Employee benefits,218.54,318.67,413.84,371.97,-22.996810,11.256284,-7.441431
Finance costs,5.11,12.37,13.84,18.34,-10.621387,-24.536532,-17.873147
Depreciation and amortization,187.23,268.81,195.44,82.16,37.540933,137.877313,80.880810
Others,154.10,304.75,372.94,279.84,-18.284443,33.269011,4.355889
Total expenses,2135.85,2811.50,1742.80,1333.72,61.320863,30.672105,45.190002
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
"Profit/(Loss) before exceptional items, share of net\rprofit/(losses) of investments accounted for using the\requity method and tax",-65.79,-190.04,118.18,485.68,-260.805551,-75.667106,NaN
Share of loss of Investments accounted using equity\rmethod (net),-15.92,-18.12,-9.47,-0.63,91.341077,1403.174603,436.301266
(Loss)/profit before exceptional items and tax,-81.71,-208.16,108.71,485.05,-291.481924,-77.587878,NaN
Exceptional items,NaN,NaN,NaN,-357.18,0.000000,0.000000,0.000000
(Loss)/profit before tax,-81.71,-208.16,108.71,127.87,-291.481924,-14.983968,NaN
Tax expense:,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Current tax,45.81,55.57,69.65,143.65,-20.215363,-51.514097,-37.803294
Deferred tax,-26.45,2.42,-28.07,-26.01,-108.621304,7.920031,NaN
Total tax expense,19.36,57.99,41.58,117.64,39.466089,-64.654879,-29.789988
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Net (loss)/profit,-101.07,-266.15,67.13,10.23,-496.469537,556.207234,NaN
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Other comprehensive income,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Items that will not be reclassified to profit and loss:,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Re-measurements of defined employee benefit plans,0.34,1.00,-1.69,0.21,-159.171598,-904.761905,118.217890
Income tax relating to items that will not be reclassified to\rprofit or loss,-0.38,-0.27,-0.45,-0.07,-40.000000,542.857143,96.396101
Items that may be reclassified to profit or loss:,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Net profit/(loss) on FVOCI debt instruments,-1.34,14.38,0.23,-1.31,6152.173913,-117.557252,NaN
Exchange differences in translating the financial\rstatements of a foreign operation,-41.38,146.19,114.81,16.81,27.332114,582.986318,194.900138
Income tax relating to items that will be reclassified to\rprofit and loss,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Total other comprehensive income/(loss),-42.46,161.30,112.90,15.64,42.869796,621.867008,221.143258
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Total comprehensive income/(loss),-143.53,-104.85,180.03,25.87,-158.240293,595.902590,NaN
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Profit/(loss) attributable to:,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
(i) Equity holders of the Company,-50.15,-21.26,175.08,26.70,-112.143020,555.730337,NaN
(ii) Non-controlling interest,-50.92,-244.89,-107.95,-16.47,126.855025,555.434123,285.601510
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Other comprehensive income/(loss) attributable to:,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
(i) Equity holders of the Company,-42.46,161.30,112.90,15.64,42.869796,621.867008,221.143258
(ii) Non-controlling interest,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Total comprehensive income/(loss) attributable to:,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
(i) Equity holders of the Company,-92.61,140.04,287.98,42.34,-51.371623,580.160605,81.865627
(ii) Non-controlling interest,-50.92,-244.89,-107.95,-16.47,126.855025,555.434123,285.601510
nan,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Earnings per equity share (nominal value of 4 each):,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
Basic,-1.78,-0.77,6.39,1.05,-112.050078,508.571429,NaN
Diluted,-1.78,-0.77,6.27,1.04,-112.280702,502.884615,NaN

In [13]:
# Assuming indexed_df is your DataFrame

# Temporarily reset the index for styling
temp_df = indexed_df.reset_index()

# Convert string 'nan' to actual NaN values in 'Profit and Loss' column
temp_df['Profit and Loss'] = temp_df['Profit and Loss'].replace('nan', np.nan)

# Drop rows where 'Profit and Loss' column contains NaN
temp_df = temp_df.dropna(subset=['Profit and Loss'])

# Define the styling function to apply bold only to rows where the index contains 'Total'
def bold_if_total_in_index(row):
    if 'Total' in row['Profit and Loss']:
        return ['font-weight: bold'] * len(row)
    else:
        return [''] * len(row)

# Apply the styling
styled_df = temp_df.style.apply(bold_if_total_in_index, axis=1)

# Assume 'numeric_columns' is a list of the names of your numeric columns
numeric_columns = ['As at September 30, 2020', 'As at March 31, 2020', 'As at March 31, 2019', 'As at March 31, 2018', 'YoY 2019-2020', 'YoY 2018-2019', 'CAGR']

# Apply number formatting only to numeric columns
styled_df = styled_df.format({col: "{:.2f}" for col in numeric_columns})

# Display the styled DataFrame
styled_df

In [ ]:
# Define the path where you want to save the Excel file
file_path = '/Users/mohjaiswal/Desktop/ArthyaInvest/PNL_financial_statement1.xlsx'  # Update this to your desired path

# Save the styled DataFrame to Excel at the specified path
styled_df.to_excel(file_path, engine='openpyxl', index=False)